ayn_password: 'foobarbaz'
ray_password: 'foobarbaz'
wordpress_mysql_user_passwd: foobarbaz
aws_access_key_id: foobarbaz
aws_secret_access_key: foobarbaz/foobarbaz
mysql_root_password: 'foobarbaz'
wordpress_version: 3.7.1


ubuntu_release: 'precise'
logwatch_email: 'ops@aynassociates.com'

# php.ini
php_max_execution_time: '90'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_html_errors: 'On'
php_post_max_size: '32M'
php_upload_max_filesize: '32M'
php_date_timezone: 'Europe/London'
php_memory_limit: '512M'

# apc.ini
apc_rfc1867: '1'
apc_shm_size: '256M'
apc_shm_segments: '1'
apc_num_files_hint: '0'

# my.cnf
mysql_max_allowed_packet: '128M'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'
innodb_file_per_table: 'innodb_file_per_table'

# apache
apache_server_admin: 'ops@aynassociates.com'
#apache_server_alias: '*.carmudgeons.com'

# vsftpd
vsftpd_anonymous_enable: 'NO'
vsftpd_local_enable: 'YES'
vsftpd_write_enable: 'YES'
vsftpd_local_umask: '002'
